/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain;

/**
 *
 * @author Verniy
 */
public class Customer {

    private String ID;
    private String name;
    private String email;
    private String dob;
    private String password;

    public Customer() {
    }
    
    public Customer(String name, String email, String dob, String password) {
        //ID generated by database
        this.name = name;
        this.email = email;
        this.dob = dob;
        this.password = password;
    }
    
    public Customer(String id, String name, String email, String dob, String password) {
        this.ID = id;
        this.name = name;
        this.email = email;
        this.dob = dob;
        this.password = password;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
